# Site settings
title: Open Data Handbook
email: admin@okfn.org
description: > # this means to ignore newlines until "baseurl:"
  A collection of research, resources, use cases and guides for civil society and government on the “what, why & how” of open data. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://new.opendatahandbook.org" # the base hostname & protocol for your site
github_username:  okfn
github_repo:  opendatahandbook-v2

# Build settings
markdown: kramdown

permalink: pretty

defaults: 
#en
  - 
    scope: #this should be removed once more specific paths are defined
      path: ""
    values: 
      section: Guide
      layout: page
      edit: true
  -
    scope: 
      path: "en"
    values: 
      lang: en
  -   
    scope: 
      path: "en/guide"
    values: 
      section: Guide
      layout: page
      edit: true
  -  
    scope: 
      path: "contribute" 
    values: 
      section: Contribute
      layout: docs
      edit: true
  - 
    scope: 
      type: "posts"
    values:
      section: Value Stories
      permalink: /value-stories/:title/
      layout: post
      edit: true
#de
  - 
    scope: 
      path: "de"
    values: 
      lang: de
  -   
    scope: 
      path: "de/guide"
    values: 
      section: Guide
      layout: page
      edit: true 

collections:
  - resources
